apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash-syslog
  namespace: monitoring
  labels:
    app: logstash-syslog
spec:
  selector:
    matchLabels:
      app: logstash-syslog
  template:
    metadata:
      labels:
        app: logstash-syslog
    spec:
      containers:
      - name: logstash
        image: <your repo>/logstash:v7.9.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9600
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /usr/share/logstash/config/
          name: config
      serviceAccount: logstash-syslog
      serviceAccountName: logstash-syslog
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config
        configMap:
          name: logstash-config