apiVersion: v1
kind: Service
metadata:
  labels:
    app: logstash-syslog
  name: logstash-syslog
  namespace: monitoring
spec:
  ports:
  - name: http-logstash-syslog
    port: 9600
    protocol: TCP
    targetPort: 9600
  selector:
    app: logstash-syslog
  sessionAffinity: None
  type: ClusterIP